language: android
android:
  components:
    - platform-tools
    - tools

    - build-tools-26.0.2

    - android-26

    - extra-google-m2repository
    - extra-android-m2repository

jdk:
  - oraclejdk8

script:
  - ./gradlew test
